Repository kubermatic/fubectl, pull requests merged in 2021-05, with the labels that each got.

#68 xargs and msys2 improvements
  fubectl.source
Labels: approved, dco-signoff: yes, lgtm, size/S

#69 Kubectl native secret viewer
  fubectl.source
Labels: approved, dco-signoff: yes, lgtm, size/S

#71 feat: pod as default kind for selection
  fubectl.source
Labels: approved, dco-signoff: yes, lgtm, size/S

#72 feat: editorconfig and indentation fix
  .editorconfig
  fubectl.source
Labels: approved, dco-signoff: yes, lgtm, size/M

#73 fix: rollback special msys hack
  fubectl.source
Labels: approved, dco-signoff: yes, lgtm, size/XS

#74 feat(initial): separate aliases scope to current NS and entire cluster
  fubectl.source
Labels: approved, dco-signoff: yes, lgtm, size/S

#77 feat: separate aliases scope to current NS and entire cluster
  fubectl.source
Labels: approved, dco-signoff: yes, lgtm, size/L

#75 Explicit dependency on kubectl plugins in README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
